### ISSUE TITLE
Redesign notification model

### ISSUE THREAD

**Issue by Bobbyjuba** [umkc-cs-451-2020-spring/semester-project-group-6#75]
Changed the notification model as well as the procedures to allow for the transaction ID to be displayed in the Json. Now, a specific transaction can be viewed from the notification attached to it.

**Comment by digital-slime** [comment]
Is there a way to link issues? mine very much depends on yours being done.

**Comment by lstirkUMKC** [comment]
Are we still using ints for the ID or were they switched to GUID's?

**Comment by lstirkUMKC** [comment]
> Is there a way to link issues? mine very much depends on yours being done.

I'm not sure what you mean.

**Comment by Bobbyjuba** [comment]
> Are we still using ints for the ID or were they switched to GUID's?

It's an int that auto-increments with every entry in the transaction DB, so it acts as a GUID

**Comment by lstirkUMKC** [comment]
Okay. One of the issues opened was to add GUID to the notification table. I was just checking whether you meant the GUID/UUID data type, but I see they're still ints 👌

**Comment by Bobbyjuba** [comment]
> Okay. One of the issues opened was to add GUID to the notification table. I was just checking whether you meant the GUID/UUID data type, but I see they're still ints 👌

My bad I saw that after I added this... Lol
